[view]
theme = "dark.toml"
font_family = ""
font_family_text = ""
animations = false
language = "en"
notifications = true
welcome_logo = "src/assets/images/knight.png"
welcome_logo_width =300
welcome_logo_height = 300

window_opacity = 1.0
window_startup_animations = false

[database]
autoSave = true
database_dir = "Passwords/"
backup_dir = "Backups/"
backup = true
backup_time = "1d"

[privacy]
auto_hide_passwords = true
confirm_password = true

[hotkeys]
new_password = "Ctrl+N"
edit_password = "Ctrl+E"
del_password = "Ctrl+Backspace"
hide_password = "Ctrl+G"
settings = "Ctrl+I"
hide_tree = ""
