[view]
theme = "dark.toml"
animations = true
background = "solid"
background_opacity = 0.1
language = "en"

[database]
autoSave = true
auto_hide_passwords = true
database_dir = "Passwords/"
download_dir = ""

[notification]
new_version_notification = true

[hotkeys]
new_password = "Ctrl+N"
edit_password = "Ctrl+E"
del_password = "Ctrl+Backspace"
hide_password = "Ctrl+G"
settings = "Ctrl+I"
hide_tree = ""
up = ""
down = ""
left = ""
right = ""
