[main]
background = "#B7B7B7" #151515
text       = "#222"
border     = "#EEE"
icons      = "#222"

[buttons]
btn_background = "#D3D3D3"
btn_border     = "#EEE"
btn_icons      = "#D3D3D3"
btn_background_hover = "#222222"
btn_border_hover = "#626262"

[toolbar]
tool_background = "#D3D3D3"
tool_border = "#EEE"

[tree]
tree_background = "#D3D3D3"
tree_text       = "#222222"
tree_border     = "#EEE"
tree_selection  = "#333333"
tree_selection_text = "#C7C7C7"

[search]
search_backgorund = "#D3D3D3"
serach_background_pressed = ""
serach_backgorund_focus = ""
search_text = "#111"
serach_border = "#EEE"

[right_workspace]
r_workspace_background = "#D3D3D3"
r_workspace_text = "#eee"
r_workspace_border = "#EEE"

[dialogs]
background = "#151515"
accient = "#D3D3D3"
border = "#222222"
icons = "#D3D3D3"