[main]
background = "#151515"
foreground = "#111111"
text       = "#C7C7C7"
border     = "#222222"
icons      = "#D3D3D3"

[buttons]
btn_background = "#111111"
btn_border     = "#222222"
btn_icons      = "#D3D3D3"
btn_background_hover = "#222222"
btn_border_hover = "#626262"

[toolbar]
tool_background = "#111111"
tool_border = "#222222"

[tree]
tree_background = "#111111"
tree_text       = "#D3D3D3"
tree_border     = "#222222"
tree_selection  = "#333333"
tree_selection_text = "#C7C7C7"

[search]
search_backgorund = "#111111"
serach_background_pressed = ""
serach_backgorund_focus = ""
search_text = "#D3D3D3"
serach_border = "#222222"

[right_workspace]
r_workspace_background = "#111111"
r_workspace_border = "#222222"

[dialogs]
dialog_background = "#151515"